(function(){'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const labels={home:'Home',create:'Create',projects:'Projects',templates:'Templates',assets:'Assets',director:'AI Director',score:'Score',brand:'Brand DNA',experiments:'Experiments',analytics:'Analytics',advisor:'AI Advisor',brandkit:'Brand Kit',team:'Team',billing:'Billing',settings:'Settings',editor:'Editor'};
let route='home',templates=[{name:'Reveal',description:'Curiosity-led, single subject.',copy:'THE TRUTH / ABOUT IT'},{name:'Experiment',description:'Strong for reviews and tests.',copy:'I TRIED / THIS'},{name:'Transformation',description:'Before and after without clutter.',copy:'FROM STUCK / TO FLOW'},{name:'Framework',description:'Authority with readable structure.',copy:'3 RULES / THAT CHANGED IT'}],projects=[];
function icons(){window.lucide?.createIcons?.()}
function toast(m){let t=$('#toast');if(!t){t=document.createElement('div');t.id='preview-toast';Object.assign(t.style,{position:'fixed',left:'50%',bottom:'24px',zIndex:99,transform:'translateX(-50%)',padding:'12px 15px',border:'1px solid var(--line)',borderRadius:'11px',background:'var(--surface3)',color:'var(--ink)',fontSize:'12px',boxShadow:'var(--shadow)'});document.body.appendChild(t)}t.textContent=m;t.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>t.classList.remove('show'),2400)}
function go(next){if(!$('#view-'+next))next='home';route=next;$$('.view').forEach(v=>v.classList.toggle('active',v.id==='view-'+next));$$('[data-route]').forEach(b=>b.classList.toggle('active',b.dataset.route===next));if($('#crumbPage'))$('#crumbPage').textContent=labels[next]||next;if($('#crumbSection'))$('#crumbSection').textContent=next==='editor'?'Project':['director','score','brand','experiments','analytics','advisor'].includes(next)?'Intelligence':['brandkit','team','billing','settings'].includes(next)?'Settings':'Workspace';window.scrollTo(0,0);icons()}
function renderTemplates(){const root=$('#templateGrid');if(!root)return;root.innerHTML=templates.map((t,i)=>`<article class="template"><div class="template-art ${['a','b','c','d'][i%4]}"><strong>${t.name}</strong><span>EDITABLE / 16:9</span></div><div class="template-body"><strong>${t.name}</strong><p>${t.description}</p><div class="template-actions"><span>Preview template</span><button data-use-template="${i}">Use</button></div></div></article>`).join('')||'<div class="ti-project-empty">No templates yet.</div>';icons()}
function renderProjects(){const root=$('#projectGrid'),recent=$('#recentProjects');const card=p=>`<article class="project"><button class="thumb t1" data-open-project="${p.id}" aria-label="Open ${p.name}"><span class="thumb-badge">Draft</span><span class="thumb-label">${p.name.slice(0,12)}<br><em style="color:var(--cyan);font-style:normal">${p.platform}</em></span></button><div class="project-body"><div class="project-title"><strong>${p.name}</strong><button data-delete-project="${p.id}" aria-label="Delete ${p.name}">×</button></div><div class="project-meta"><span>${p.platform}</span><span>·</span><span>${p.status||'draft'}</span></div></div></article>`;if(root)root.innerHTML=projects.map(card).join('')||'<div class="ti-project-empty">No projects yet. Create your first thumbnail.</div>';if(recent)recent.innerHTML=projects.slice(0,3).map(card).join('')||'<div class="ti-project-empty">No projects yet. Create your first thumbnail.</div>';icons()}
function createTemplate(){const name=prompt('Template name','Untitled template');if(!name?.trim())return;templates.push({name:name.trim(),description:'Creator template',copy:'THUMBNAIL / IDEA'});renderTemplates();toast('Template created in preview mode')}
function useTemplate(i){const t=templates[i];if(!t)return;const input=$('#canvasText'),copy=t.copy;if(input)input.value=copy;if($('#canvasCopy')){const p=copy.split('/');$('#canvasCopy').innerHTML=p[0]+'<em>'+(p[1]||'')+'</em>'}go('editor');toast('Template opened in editor preview')}
function createProject(){const name=prompt('Project name','Untitled thumbnail');if(!name?.trim())return;const p={id:String(Date.now()),name:name.trim(),platform:'YouTube',status:'draft'};projects.unshift(p);renderProjects();go('editor');toast('Project created in preview mode')}
function openProject(id){const p=projects.find(x=>x.id===id);if(p){if($('#editorProjectName'))$('#editorProjectName').textContent=p.name;go('editor');toast('Project opened')}}
function exportPreview(){const c=document.createElement('canvas');c.width=1280;c.height=720;const x=c.getContext('2d');x.fillStyle='#211744';x.fillRect(0,0,c.width,c.height);x.fillStyle='#f4f1ed';x.font='800 84px Arial';const parts=($('#canvasText')?.value||'THUMBNAIL / IDEA').split('/');x.fillText(parts[0].trim(),80,570);x.fillStyle='#71e3df';x.fillText((parts[1]||'').trim(),80,660);const a=document.createElement('a');a.download='thumbnail-intelligence-preview.png';a.href=c.toDataURL('image/png');a.click();toast('Preview PNG downloaded')}
function score(){if($('#scoreValue'))$('#scoreValue').textContent='84';if($('#scoreMessage'))$('#scoreMessage').textContent='Preview score only. Connect the API for a persisted result.';toast('Preview scoring shown')}
document.addEventListener('click',e=>{const r=e.target.closest('[data-route]');if(r){e.preventDefault();go(r.dataset.route);return}const t=e.target.closest('[data-use-template]');if(t){useTemplate(Number(t.dataset.useTemplate));return}const o=e.target.closest('[data-open-project]');if(o){openProject(o.dataset.openProject);return}const d=e.target.closest('[data-delete-project]');if(d){if(confirm('Delete this preview project?')){projects=projects.filter(p=>p.id!==d.dataset.deleteProject);renderProjects();toast('Project deleted')}}const a=e.target.closest('[data-action]')?.dataset.action;if(a==='collapse'){$('#sidebar')?.classList.toggle('collapsed');return}if(a==='new-project'){createProject();return}if(a==='create-template'||a==='new-template'){createTemplate();return}if(a==='score'||a==='improve-score'){score();return}if(a==='mobile-preview'){$('#mobilePreview')?.classList.add('open');return}if(a==='close-mobile'){$('#mobilePreview')?.classList.remove('open');return}if(a==='export'){exportPreview();return}if(a==='generate-strategy'||a==='generate-director')return toast('AI provider is not connected in this preview.');if(a==='upload-image'||a==='upload-asset'||a==='upload-video')return toast('Uploads require the API/storage service.');if(a==='connect-youtube')return toast('YouTube OAuth requires server configuration.');if(a==='editor-ai'||a==='ai-action')return toast('Editor AI requires a configured provider.');if(['new-experiment','analyze-brand','save-brandkit','invite-member','billing-config'].includes(a))return toast('This feature requires the authenticated API service.');if(a==='toggle-rule'){e.target.classList.toggle('off');return}});
document.addEventListener('input',e=>{if(e.target.id==='canvasText'&&$('#canvasCopy')){const p=e.target.value.split('/');$('#canvasCopy').innerHTML=p[0]+'<em>'+(p[1]||'')+'</em>'}});document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#command')?.classList.add('open');$('#commandInput')?.focus()}if(e.key==='Escape'){$('#command')?.classList.remove('open');$('#mobilePreview')?.classList.remove('open')}});renderTemplates();renderProjects();icons();let b=document.createElement('div');b.textContent='CodeSandbox preview mode · UI state only';Object.assign(b.style,{position:'fixed',right:'18px',bottom:'18px',zIndex:50,padding:'8px 10px',border:'1px solid var(--line)',borderRadius:'9px',background:'var(--surface2)',color:'var(--muted)',fontSize:'10px'});document.body.appendChild(b);
})();
